"""update schema for Claims

Revision ID: 7d878d41dd2d
Revises: 49989e401701
Create Date: 2026-01-14 10:54:08.541113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d878d41dd2d'
down_revision: Union[str, None] = '49989e401701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'line_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('line_item_id', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
