"""updated order and claim structure

Revision ID: 9a6a79daa530
Revises: 7d878d41dd2d
Create Date: 2026-01-14 14:12:28.983661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6a79daa530'
down_revision: Union[str, None] = '7d878d41dd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity_claimed', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantity_claimed')
    # ### end Alembic commands ###
