"""renamed to order table

Revision ID: a24853937a87
Revises: 8a0528ebb7c9
Create Date: 2025-04-19 20:47:19.256014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24853937a87'
down_revision: Union[str, None] = '8a0528ebb7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_orders',
    sa.Column('order_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('material', sa.VARCHAR(), nullable=False),
    sa.Column('technique', sa.VARCHAR(), nullable=False),
    sa.Column('sizing', sa.FLOAT(), nullable=False),
    sa.Column('colour', sa.VARCHAR(), nullable=False),
    sa.Column('selectedFile', sa.VARCHAR(), nullable=False),
    sa.Column('selectedFileType', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('is_collaborative', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###
